export const actionTypes = {
  TOGGLE_MOBILE_MENU: "TOGGLE_MOBILE_MENU",
  CLOSE_MOBILE_MENU: "CLOSE_MOBILE_MENU",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  INCREASE_REFERENCES_INDEX: "INCREASE_REFERENCES_INDEX",
  DECREASE_REFERENCES_INDEX: "DECREASE_REFERENCES_INDEX",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  SET_SORTING_TYPE: "SET_SORTING_TYPE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREASE_PRODUCTS_AMOUNT: "INCREASE_PRODUCTS_AMOUNT",
  DECREASE_PRODUCTS_AMOUNT: "DECREASE_PRODUCTS_AMOUNT",
};
